# yaml-language-server: $schema=https://raw.githubusercontent.com/Luftfartsverket/reqstool-client/main/src/reqstool/resources/schemas/v1/reqstool_config.schema.jsonhttps://raw.githubusercontent.com/Luftfartsverket/reqstool-client/main/src/reqstool/resources/schemas/v1/reqstool_config.schema.json

language: java
build: maven
resources:
  requirements: requirements.yml
  software_verification_cases: software_verification_cases.yml
  manual_verification_results: manual_verification_results.yml
  annotations: ../../target/reqstool/annotations.yml
  test_results:
    - ../../target/failsafe
    - ../../target/surefire
