== Standard File and Directory Set

All files have a JSON Schema: https://github.com/Luftfartsverket/reqstool-client/tree/main/src/reqstool/resources/schemas/v1

For examples see:

* docs/examples
* unit tests: [TODO](#todo)

[[reqstool_config]]
=== reqstool_config.yml
Contains file and directory configuration used by `Reqstool`.

The layout of files and directories for a project can change using any of the following types:

* java-maven: xref:data.adoc#dynamic-directory-structure[dynamic files] are relative "../target" to the xref:data.adoc#static-directory-structure[static files]
* java-maven-docs: xref:data.adoc#dynamic-directory-structure[dynamic files] are relative "../../target" to the xref:data.adoc#static-directory-structure[static files]
* custom: custom path to xref:data.adoc#dynamic-directory-structure[dynamic files] can be set relative to the xref:data.adoc#static-directory-structure[static files]

If no reqstool_config.yml file is present in the folder that contains the xref:data.adoc#static-directory-structure[static files], Reqstool will expect all files and folders, even the dynamic ones, to reside in the path provided to the -p argument when Reqstool is run. This works well with a xref:data.adoc#maven-artifact-zip-directory-structure[Maven zip file directory structure]. 


If you are using a regular xref:data.adoc#java-maven-directory-structure[Maven] project, It is recommended to let all the xref:data.adoc#static-directory-structure[static files] be placed in a folder in the root of the project called 'requirements'. Your reqstool_config.yml file should also be placed in this folder, and would then only need to include the following:

```yaml
# yaml-language-server: $schema=https://raw.githubusercontent.com/Luftfartsverket/reqstool-client/main/src/reqstool/resources/schemas/v1/reqstool_config.schema.json

type: java-maven
```


Below is an example on how to change the default paths to the required *.yml files and folders that are generated when the artifact is produced by Maven. The path specified for should be relative to the -p argument that you provide when Reqstool is run. 

```yaml
# yaml-language-server: $schema=https://raw.githubusercontent.com/Luftfartsverket/reqstool-client/main/src/reqstool/resources/schemas/v1/reqstool_config.schema.json

type: custom 
locations:
  test_results_dirs:
    - ../target/some_folder/failsafe
    - ../target/my_folder/surefire
  annotations:
    implementations: ../target/hello/requirements_annotations_impls.yml
    tests: ../target/demo/requirements_annotations_tests.yml

```

=== requirements.yml

Contains all the requirements.

=== software_verification_cases.yml

Contains information about how specific requirements should be verified.

One of the fields to be set on a software verification case is the verification type which can be selected from five different pre-defined values (automated-test, manual-test, review, platform, other).

All but the automated-test value expects at least one manual verification entry of that particular software verification case. The automated test value expects at least one automated test should exist and preferably pass. 

=== manual_verification_results.yml
Contains information and the result of a manual verification case

=== requirement_annotations.yml

Typically generated by an annotations parser and lists all requirement annotations 

NOTE: JSON Schema

=== svcs_annotations.yml

Typically generated by an annotations parser and lists all software verification cases annotations.

=== annotations.yml

Lists all annotations, containing both requirements and software verification cases annotations.

Generated by default by python annotations parser.

Generated by Maven plugin for Java projects that combines requirements_annotations.yml and svcs_annotations.yml
