# yaml-language-server: $schema=https://raw.githubusercontent.com/Luftfartsverket/reqstool-client/main/src/reqstool/resources/schemas/v1/reqstool_config.schema.json

type: default
project_root_dir: "../.."
locations:
  annotations: ./dist/annotations.yml
  test_results_dirs:
    - "../../dist"
