# yaml-language-server: $schema=https://raw.githubusercontent.com/Luftfartsverket/reqstool-client/main/src/reqstool/resources/schemas/v1/reqstool_config.schema.json

language: python
build: hatch
resources:
  requirements: requirements.yml
  software_verification_cases: software_verification_cases.yml
  manual_verification_results: manual_verification_results.yml
  annotations: ../../build/reqstool/annotations.yml
  test_results:
    - ../../build/**/*.xml
