# yaml-language-server: $schema=https://raw.githubusercontent.com/Luftfartsverket/reqstool-client/main/src/reqstool/resources/schemas/v1/requirements.schema.json

metadata:
  urn: reqstool-client
  variant: microservice
  title: Reqstool client
  url: https://github.com/Luftfartsverket/reqstool-client

requirements:
  - id: REQ_001
    title: Indata from local files
    significance: shall
    description: Reqstool should be able to read and parse *.yml files from a local disk.
    categories: [functional-suitability]
    revision: 0.0.1
  - id: REQ_002
    title: Indata from git location
    significance: shall
    description: Reqstool should be able to fetch and parse *.yml files from a git repository.
    categories: [functional-suitability]
    revision: 0.0.1
  - id: REQ_003
    title: Indata from maven artifacts
    significance: shall
    description: Reqstool should be able to fetch, unzip and parse *.yml files from a maven artifact
    categories: [functional-suitability]
    revision: 0.0.1
  - id: REQ_004
    title: Requirement categories from ISO standard
    significance: shall
    description: Requirements shall be categorized using this ISO25000 standard for product quality. See link for further information https://iso25000.com/index.php/en/iso-25000-standards/iso-25010
    categories: [reliability]
    revision: 0.0.1
