# yaml-language-server: $schema=https://raw.githubusercontent.com/Luftfartsverket/reqstool-client/main/src/reqstool/resources/schemas/v1/requirements.schema.json

metadata:
  urn: reqstool-client
  variant: system
  title: Reqstool client
  url: https://github.com/Luftfartsverket/reqstool-client

requirements:
  - id: REQ_010
    title: Title REQ_010
    significance: may
    description: Description REQ_010
    rationale: Rationale REQ_010
    categories: [compatibility]
    revision: 0.0.1
