name: Build Docs
on:
  workflow_dispatch:
  pull_request:
    paths:
      - "docs/**"
  push:
    branches:
      - main
    paths:
      - "docs/**"

permissions:
  contents: read

jobs:
  build:
    uses: reqstool/.github/.github/workflows/common-build-docs.yml@ef815eae0bca7160cdc714126cac73f76d638b39 # 1.0.0
